
import 'package:inspector_app/Inspector_Models/payment_saved_model.dart';

import '../Inspector_Models/charge_toSave_model.dart';

PaymentSaved paySaved = PaymentSaved();
ChargeSaved chargeSaved = ChargeSaved();
String myToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJOYW1lIjoiOTg4MjQ1NjciLCJSb2xlIjoiSW5zcGVjdG9yIiwiZXhwIjoxNjUyMjU4MjA3LCJpc3MiOiJJbnZlbnRvcnlBdXRoZW50aWNhdGlvblNlcnZlciIsImF1ZCI6IkludmVudG9yeVNlcnZpY2VQb3RtYW5DbGllbnQifQ.SWZfLRXieu__d3xnAatsHsSvJB4xGMtfJbl2AhouhVA";